[package]
name = "auccalc"
version = "0.1.0"
edition = "2018"

[package.metadata.maturin]
python-source = "python"

[lib]
name = "auccalc"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.15.1", features = ["extension-module"] }

[dev-dependencies]
float-cmp = "0.9.0"
